/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.jp22.view;

import hr.edunova.jp22.controller.ObradaAlbum;
import hr.edunova.jp22.controller.ObradaClan;
import hr.edunova.jp22.controller.ObradaPjesma;
import hr.edunova.jp22.controller.ObradaUmjetnik;
import hr.edunova.jp22.model.Album;
import hr.edunova.jp22.model.Clan;
import hr.edunova.jp22.model.Pjesma;
import hr.edunova.jp22.model.Umjetnik;
import hr.edunova.jp22.utility.EdunovaException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Bole
 */
public class SpajanjeEntiteta extends javax.swing.JFrame {

    private ObradaClan obradaC;
    private ObradaUmjetnik obradaU;
    private ObradaAlbum obradaA;
    private ObradaPjesma obradaP;
    private Umjetnik entitetU;
    private Album entitetA;

    /**
     * Creates new form SpajanjeEntiteta
     */
    public SpajanjeEntiteta() {
        initComponents();
        obradaC = new ObradaClan();
        obradaU = new ObradaUmjetnik();
        obradaA = new ObradaAlbum();
        obradaP = new ObradaPjesma();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGlavni = new javax.swing.JPanel();
        tabSpajanje = new javax.swing.JTabbedPane();
        pnlUC = new javax.swing.JPanel();
        txtTraziClan = new javax.swing.JTextField();
        btnPridruziClan = new javax.swing.JButton();
        btnUkloniClan = new javax.swing.JButton();
        btnTraziClan = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstPridruzenClan = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstTraziClan = new javax.swing.JList<>();
        btnPrimjeniUC = new javax.swing.JButton();
        llblGlavniUmjetnikC = new javax.swing.JLabel();
        lblPridruzenClan = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstGlavniUmjetnikC = new javax.swing.JList<>();
        jSeparator13 = new javax.swing.JSeparator();
        pnlUA = new javax.swing.JPanel();
        txtTraziAlbum = new javax.swing.JTextField();
        btnPridruziAlbum = new javax.swing.JButton();
        btnUkloniAlbum = new javax.swing.JButton();
        btnTraziAlbum = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        lstPridruzenAlbum = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        lstTraziAlbum = new javax.swing.JList<>();
        btnPrimjeniUA = new javax.swing.JButton();
        llblGlavniUmjetnikA = new javax.swing.JLabel();
        lblPridruzenAlbum = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane12 = new javax.swing.JScrollPane();
        lstGlavniUmjetnikA = new javax.swing.JList<>();
        jSeparator14 = new javax.swing.JSeparator();
        pnlAP = new javax.swing.JPanel();
        txtTraziPjesma = new javax.swing.JTextField();
        btnPridruziPjesma = new javax.swing.JButton();
        btnUkloniPjesma = new javax.swing.JButton();
        btnTraziPjesma = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        lstPridruzenPjesma = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        lstTraziPjesma = new javax.swing.JList<>();
        btnPrimjeniAP = new javax.swing.JButton();
        llblGlavniAlbumP = new javax.swing.JLabel();
        lblPridruzenPjesma = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane15 = new javax.swing.JScrollPane();
        lstGlavniAlbumP = new javax.swing.JList<>();
        jSeparator15 = new javax.swing.JSeparator();
        btnOdjava3 = new javax.swing.JButton();
        btnUmjetnikClan2 = new javax.swing.JButton();
        btnUmjetnikAlbum2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGlavni.setBackground(new java.awt.Color(0, 0, 153));
        pnlGlavni.setPreferredSize(new java.awt.Dimension(875, 661));

        tabSpajanje.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabSpajanje.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabSpajanje.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabSpajanje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pnlUC.setBackground(new java.awt.Color(0, 0, 153));

        btnPridruziClan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPridruziClan.setForeground(new java.awt.Color(0, 0, 102));
        btnPridruziClan.setText("->");
        btnPridruziClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridruziClanActionPerformed(evt);
            }
        });

        btnUkloniClan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUkloniClan.setForeground(new java.awt.Color(0, 0, 102));
        btnUkloniClan.setText("<-");
        btnUkloniClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniClanActionPerformed(evt);
            }
        });

        btnTraziClan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTraziClan.setText("¤");
        btnTraziClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziClanActionPerformed(evt);
            }
        });

        lstPridruzenClan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPridruzenClanValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(lstPridruzenClan);

        lstTraziClan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTraziClanValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(lstTraziClan);

        btnPrimjeniUC.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPrimjeniUC.setText("Primjeni");
        btnPrimjeniUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimjeniUCActionPerformed(evt);
            }
        });

        llblGlavniUmjetnikC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        llblGlavniUmjetnikC.setForeground(new java.awt.Color(255, 255, 255));
        llblGlavniUmjetnikC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llblGlavniUmjetnikC.setText("Umjetnik");

        lblPridruzenClan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPridruzenClan.setForeground(new java.awt.Color(255, 255, 255));
        lblPridruzenClan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPridruzenClan.setText("Član");

        lstGlavniUmjetnikC.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGlavniUmjetnikCValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(lstGlavniUmjetnikC);

        javax.swing.GroupLayout pnlUCLayout = new javax.swing.GroupLayout(pnlUC);
        pnlUC.setLayout(pnlUCLayout);
        pnlUCLayout.setHorizontalGroup(
            pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUCLayout.createSequentialGroup()
                        .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(llblGlavniUmjetnikC, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnPrimjeniUC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUCLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPridruziClan)
                            .addComponent(btnUkloniClan)))
                    .addGroup(pnlUCLayout.createSequentialGroup()
                        .addComponent(txtTraziClan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTraziClan))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addComponent(lblPridruzenClan, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUCLayout.setVerticalGroup(
            pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUCLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnPridruziClan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnUkloniClan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUCLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnPrimjeniUC))
                    .addGroup(pnlUCLayout.createSequentialGroup()
                        .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llblGlavniUmjetnikC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTraziClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTraziClan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPridruzenClan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSpajanje.addTab("Umjetnik_Član", pnlUC);

        pnlUA.setBackground(new java.awt.Color(0, 0, 153));

        btnPridruziAlbum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPridruziAlbum.setForeground(new java.awt.Color(0, 0, 102));
        btnPridruziAlbum.setText("->");
        btnPridruziAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridruziAlbumActionPerformed(evt);
            }
        });

        btnUkloniAlbum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUkloniAlbum.setForeground(new java.awt.Color(0, 0, 102));
        btnUkloniAlbum.setText("<-");
        btnUkloniAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniAlbumActionPerformed(evt);
            }
        });

        btnTraziAlbum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTraziAlbum.setText("¤");
        btnTraziAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziAlbumActionPerformed(evt);
            }
        });

        lstPridruzenAlbum.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPridruzenAlbumValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(lstPridruzenAlbum);

        lstTraziAlbum.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTraziAlbumValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(lstTraziAlbum);

        btnPrimjeniUA.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPrimjeniUA.setText("Primjeni");
        btnPrimjeniUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimjeniUAActionPerformed(evt);
            }
        });

        llblGlavniUmjetnikA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        llblGlavniUmjetnikA.setForeground(new java.awt.Color(255, 255, 255));
        llblGlavniUmjetnikA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llblGlavniUmjetnikA.setText("Umjetnik");

        lblPridruzenAlbum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPridruzenAlbum.setForeground(new java.awt.Color(255, 255, 255));
        lblPridruzenAlbum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPridruzenAlbum.setText("Album");

        lstGlavniUmjetnikA.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGlavniUmjetnikAValueChanged(evt);
            }
        });
        jScrollPane12.setViewportView(lstGlavniUmjetnikA);

        javax.swing.GroupLayout pnlUALayout = new javax.swing.GroupLayout(pnlUA);
        pnlUA.setLayout(pnlUALayout);
        pnlUALayout.setHorizontalGroup(
            pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUALayout.createSequentialGroup()
                        .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(llblGlavniUmjetnikA, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnPrimjeniUA, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUALayout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPridruziAlbum)
                            .addComponent(btnUkloniAlbum)))
                    .addGroup(pnlUALayout.createSequentialGroup()
                        .addComponent(txtTraziAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTraziAlbum))
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator7)
                    .addComponent(lblPridruzenAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUALayout.setVerticalGroup(
            pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUALayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnPridruziAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnUkloniAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUALayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnPrimjeniUA))
                    .addGroup(pnlUALayout.createSequentialGroup()
                        .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llblGlavniUmjetnikA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTraziAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTraziAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPridruzenAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSpajanje.addTab("Umjetnik_Album", pnlUA);

        pnlAP.setBackground(new java.awt.Color(0, 0, 153));

        btnPridruziPjesma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPridruziPjesma.setForeground(new java.awt.Color(0, 0, 102));
        btnPridruziPjesma.setText("->");
        btnPridruziPjesma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridruziPjesmaActionPerformed(evt);
            }
        });

        btnUkloniPjesma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUkloniPjesma.setForeground(new java.awt.Color(0, 0, 102));
        btnUkloniPjesma.setText("<-");
        btnUkloniPjesma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniPjesmaActionPerformed(evt);
            }
        });

        btnTraziPjesma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTraziPjesma.setText("¤");
        btnTraziPjesma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziPjesmaActionPerformed(evt);
            }
        });

        lstPridruzenPjesma.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPridruzenPjesmaValueChanged(evt);
            }
        });
        jScrollPane13.setViewportView(lstPridruzenPjesma);

        lstTraziPjesma.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTraziPjesmaValueChanged(evt);
            }
        });
        jScrollPane14.setViewportView(lstTraziPjesma);

        btnPrimjeniAP.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPrimjeniAP.setText("Primjeni");
        btnPrimjeniAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimjeniAPActionPerformed(evt);
            }
        });

        llblGlavniAlbumP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        llblGlavniAlbumP.setForeground(new java.awt.Color(255, 255, 255));
        llblGlavniAlbumP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llblGlavniAlbumP.setText("Album");

        lblPridruzenPjesma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPridruzenPjesma.setForeground(new java.awt.Color(255, 255, 255));
        lblPridruzenPjesma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPridruzenPjesma.setText("Pjesma");

        lstGlavniAlbumP.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGlavniAlbumPValueChanged(evt);
            }
        });
        jScrollPane15.setViewportView(lstGlavniAlbumP);

        javax.swing.GroupLayout pnlAPLayout = new javax.swing.GroupLayout(pnlAP);
        pnlAP.setLayout(pnlAPLayout);
        pnlAPLayout.setHorizontalGroup(
            pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAPLayout.createSequentialGroup()
                        .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(llblGlavniAlbumP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnPrimjeniAP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAPLayout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPridruziPjesma)
                            .addComponent(btnUkloniPjesma)))
                    .addGroup(pnlAPLayout.createSequentialGroup()
                        .addComponent(txtTraziPjesma, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTraziPjesma))
                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator9)
                    .addComponent(lblPridruzenPjesma, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAPLayout.setVerticalGroup(
            pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAPLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnPridruziPjesma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnUkloniPjesma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAPLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnPrimjeniAP))
                    .addGroup(pnlAPLayout.createSequentialGroup()
                        .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llblGlavniAlbumP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTraziPjesma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTraziPjesma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPridruzenPjesma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jScrollPane14)
                            .addComponent(jScrollPane13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSpajanje.addTab("Album_Pjesma", pnlAP);

        btnOdjava3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnOdjava3.setText("Odjavite se");
        btnOdjava3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjava3ActionPerformed(evt);
            }
        });

        btnUmjetnikClan2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnUmjetnikClan2.setText("Umjetnik_Član");
        btnUmjetnikClan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmjetnikClan2ActionPerformed(evt);
            }
        });

        btnUmjetnikAlbum2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnUmjetnikAlbum2.setText("Umjetnik_Album");
        btnUmjetnikAlbum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmjetnikAlbum2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGlavniLayout = new javax.swing.GroupLayout(pnlGlavni);
        pnlGlavni.setLayout(pnlGlavniLayout);
        pnlGlavniLayout.setHorizontalGroup(
            pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlavniLayout.createSequentialGroup()
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabSpajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGlavniLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnUmjetnikAlbum2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnUmjetnikClan2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOdjava3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlGlavniLayout.setVerticalGroup(
            pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlavniLayout.createSequentialGroup()
                .addComponent(tabSpajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUmjetnikClan2)
                    .addComponent(btnOdjava3)
                    .addComponent(btnUmjetnikAlbum2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGlavni, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGlavni, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimjeniUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimjeniUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimjeniUCActionPerformed

    private void lstGlavniUmjetnikCValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGlavniUmjetnikCValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstGlavniUmjetnikCValueChanged

    private void btnTraziClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziClanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTraziClanActionPerformed

    private void btnUkloniClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniClanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUkloniClanActionPerformed

    private void btnPridruziClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridruziClanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPridruziClanActionPerformed

    private void btnUmjetnikClan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmjetnikClan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUmjetnikClan2ActionPerformed

    private void btnUmjetnikAlbum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmjetnikAlbum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUmjetnikAlbum2ActionPerformed

    private void btnOdjava3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjava3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOdjava3ActionPerformed

    private void btnPridruziAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridruziAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPridruziAlbumActionPerformed

    private void btnUkloniAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUkloniAlbumActionPerformed

    private void btnTraziAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTraziAlbumActionPerformed

    private void btnPrimjeniUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimjeniUAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimjeniUAActionPerformed

    private void lstGlavniUmjetnikAValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGlavniUmjetnikAValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstGlavniUmjetnikAValueChanged

    private void btnPridruziPjesmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridruziPjesmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPridruziPjesmaActionPerformed

    private void btnUkloniPjesmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniPjesmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUkloniPjesmaActionPerformed

    private void btnTraziPjesmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziPjesmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTraziPjesmaActionPerformed

    private void btnPrimjeniAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimjeniAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimjeniAPActionPerformed

    private void lstGlavniAlbumPValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGlavniAlbumPValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstGlavniAlbumPValueChanged

    private void lstTraziClanValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTraziClanValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstTraziClanValueChanged

    private void lstPridruzenClanValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPridruzenClanValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstPridruzenClanValueChanged

    private void lstTraziAlbumValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTraziAlbumValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstTraziAlbumValueChanged

    private void lstPridruzenAlbumValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPridruzenAlbumValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstPridruzenAlbumValueChanged

    private void lstTraziPjesmaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTraziPjesmaValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstTraziPjesmaValueChanged

    private void lstPridruzenPjesmaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPridruzenPjesmaValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstPridruzenPjesmaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpajanjeEntiteta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpajanjeEntiteta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpajanjeEntiteta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpajanjeEntiteta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpajanjeEntiteta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjava3;
    private javax.swing.JButton btnPridruziAlbum;
    private javax.swing.JButton btnPridruziClan;
    private javax.swing.JButton btnPridruziPjesma;
    private javax.swing.JButton btnPrimjeniAP;
    private javax.swing.JButton btnPrimjeniUA;
    private javax.swing.JButton btnPrimjeniUC;
    private javax.swing.JButton btnTraziAlbum;
    private javax.swing.JButton btnTraziClan;
    private javax.swing.JButton btnTraziPjesma;
    private javax.swing.JButton btnUkloniAlbum;
    private javax.swing.JButton btnUkloniClan;
    private javax.swing.JButton btnUkloniPjesma;
    private javax.swing.JButton btnUmjetnikAlbum2;
    private javax.swing.JButton btnUmjetnikClan2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblPridruzenAlbum;
    private javax.swing.JLabel lblPridruzenClan;
    private javax.swing.JLabel lblPridruzenPjesma;
    private javax.swing.JLabel llblGlavniAlbumP;
    private javax.swing.JLabel llblGlavniUmjetnikA;
    private javax.swing.JLabel llblGlavniUmjetnikC;
    private javax.swing.JList<Album> lstGlavniAlbumP;
    private javax.swing.JList<Umjetnik> lstGlavniUmjetnikA;
    private javax.swing.JList<Umjetnik> lstGlavniUmjetnikC;
    private javax.swing.JList<Album> lstPridruzenAlbum;
    private javax.swing.JList<Clan> lstPridruzenClan;
    private javax.swing.JList<Pjesma> lstPridruzenPjesma;
    private javax.swing.JList<Album> lstTraziAlbum;
    private javax.swing.JList<Clan> lstTraziClan;
    private javax.swing.JList<Pjesma> lstTraziPjesma;
    private javax.swing.JPanel pnlAP;
    private javax.swing.JPanel pnlGlavni;
    private javax.swing.JPanel pnlUA;
    private javax.swing.JPanel pnlUC;
    private javax.swing.JTabbedPane tabSpajanje;
    private javax.swing.JTextField txtTraziAlbum;
    private javax.swing.JTextField txtTraziClan;
    private javax.swing.JTextField txtTraziPjesma;
    // End of variables declaration//GEN-END:variables


    private void ucitajPodatkeU() {
        DefaultListModel<Umjetnik> m = new DefaultListModel<>();
        obradaU.getPodaci().forEach(s -> m.addElement(s));
        //lstGlavni.setModel(m);
    }

     private void ucitajPodatkeA() {
//        lstGlavni.;
//        DefaultListModel<Album> m = new DefaultListModel<>();
//        obradaA.getPodaci().forEach(s -> m.addElement(s));
//        lstGlavni.setModel(m);
    }
    
    
    private void ucitajClanove() {
        //DefaultListModel<Clan> m = new DefaultListModel<>();

        //obradaC.getPodaci(txtTrazi.getText()).forEach(s -> m.addElement(s));

        //lstTrazi.setModel(m);
    }
    
    private void ucitajPjesme() {
       // DefaultListModel<Pjesma> m = new DefaultListModel<>();

        //obradaC.getPodaci(txtTrazi.getText()).forEach(s -> m.addElement(s));

        //lstTrazi.setModel(m);
    }
    
    private void ucitajAlbume() {
       // DefaultListModel<Album> m = new DefaultListModel<>();

        //obradaC.getPodaci(txtTrazi.getText()).forEach(s -> m.addElement(s));

        //lstTrazi.setModel(m);
    }


}
