/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.jp22.view;

import hr.edunova.jp22.controller.ObradaAlbum;
import hr.edunova.jp22.controller.ObradaClan;
import hr.edunova.jp22.controller.ObradaPjesma;
import hr.edunova.jp22.controller.ObradaUmjetnik;
import hr.edunova.jp22.model.Album;
import hr.edunova.jp22.model.Clan;
import hr.edunova.jp22.model.Umjetnik;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bole
 */
public class SpajanjeEntiteta extends javax.swing.JFrame {

    private ObradaClan obradaC;
    private ObradaUmjetnik obradaU;
    private ObradaAlbum obradaA;
    private ObradaPjesma obradaP;
    private Umjetnik entitetU;
    private Album entitetA;

    /**
     * Creates new form SpajanjeEntiteta
     */
    public SpajanjeEntiteta() {
        initComponents();
        obradaC = new ObradaClan();
        obradaU = new ObradaUmjetnik();
        obradaA = new ObradaAlbum();
        obradaP = new ObradaPjesma();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTrazi = new javax.swing.JTextField();
        btnPridruzi = new javax.swing.JButton();
        btnUkloni = new javax.swing.JButton();
        btnTrazi = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPridruzi = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstGlavni = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstTrazi = new javax.swing.JList<>();
        btnOdjava = new javax.swing.JButton();
        btnPrimjeni = new javax.swing.JButton();
        llblGlavni = new javax.swing.JLabel();
        lblPridruzi = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnUmjetnikClan = new javax.swing.JButton();
        btnUmjetnikAlbum = new javax.swing.JButton();
        btnAlbumPjesma = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        btnPridruzi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPridruzi.setForeground(new java.awt.Color(0, 0, 102));
        btnPridruzi.setText("->");
        btnPridruzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridruziActionPerformed(evt);
            }
        });

        btnUkloni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUkloni.setForeground(new java.awt.Color(0, 0, 102));
        btnUkloni.setText("<-");

        btnTrazi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTrazi.setText("¤");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lstPridruzi);

        jScrollPane5.setViewportView(lstGlavni);

        jScrollPane6.setViewportView(lstTrazi);

        btnOdjava.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnOdjava.setText("Odjavite se");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        btnPrimjeni.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPrimjeni.setText("Primjeni");
        btnPrimjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimjeniActionPerformed(evt);
            }
        });

        llblGlavni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        llblGlavni.setForeground(new java.awt.Color(255, 255, 255));
        llblGlavni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llblGlavni.setText("Umjetnik");

        lblPridruzi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPridruzi.setForeground(new java.awt.Color(255, 255, 255));
        lblPridruzi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPridruzi.setText("Član");

        btnUmjetnikClan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnUmjetnikClan.setText("Umjetnik_Član");
        btnUmjetnikClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmjetnikClanActionPerformed(evt);
            }
        });

        btnUmjetnikAlbum.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnUmjetnikAlbum.setText("Umjetnik_Album");
        btnUmjetnikAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmjetnikAlbumActionPerformed(evt);
            }
        });

        btnAlbumPjesma.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAlbumPjesma.setText("Album_Pjesma");
        btnAlbumPjesma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumPjesmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUmjetnikClan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUmjetnikAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlbumPjesma, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(llblGlavni, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnPrimjeni, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPridruzi)
                            .addComponent(btnUkloni)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrazi)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPridruzi, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnPridruzi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnUkloni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTrazi)
                            .addComponent(btnTrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnPrimjeni)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(llblGlavni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPridruzi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnUmjetnikClan)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUmjetnikAlbum)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAlbumPjesma)
                                        .addGap(270, 270, 270)
                                        .addComponent(btnOdjava)
                                        .addContainerGap())
                                    .addComponent(jScrollPane4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane5))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPridruziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridruziActionPerformed

    }//GEN-LAST:event_btnPridruziActionPerformed

    private void btnUmjetnikClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmjetnikClanActionPerformed
        ucitajPodatkeU();
        lstGlavni.setCellRenderer(new UmjetniciCellRenderer());
        
    }//GEN-LAST:event_btnUmjetnikClanActionPerformed

    private void btnUmjetnikAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmjetnikAlbumActionPerformed
        ucitajPodatkeU();
        lstGlavni.setCellRenderer(new UmjetniciCellRenderer());
    }//GEN-LAST:event_btnUmjetnikAlbumActionPerformed

    private void btnAlbumPjesmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumPjesmaActionPerformed
        ucitajPodatkeU();
        lstGlavni.setCellRenderer(new UmjetniciCellRenderer());
    }//GEN-LAST:event_btnAlbumPjesmaActionPerformed

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
        ucitajClanove();
        lstTrazi.setCellRenderer(new ClanCellRenderer());
    }//GEN-LAST:event_btnTraziActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
       Izbornik izbornik = new Izbornik();
        izbornik.setLocationRelativeTo(null);
        izbornik.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void btnPrimjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimjeniActionPerformed
//        entitet.setPolaznici(new ArrayList<>());
//        DefaultListModel<Clan> m = (DefaultListModel<Clan>) lstPolazniciNaGrupi.getModel();
//        for (int i = 0; i < m.size(); i++) {
//            entitet.getPolaznici().add(m.getElementAt(i));
//        }
//
//        obrada.setEntitet(entitet);
    }//GEN-LAST:event_btnPrimjeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpajanjeEntiteta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpajanjeEntiteta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpajanjeEntiteta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpajanjeEntiteta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpajanjeEntiteta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlbumPjesma;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JButton btnPridruzi;
    private javax.swing.JButton btnPrimjeni;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JButton btnUkloni;
    private javax.swing.JButton btnUmjetnikAlbum;
    private javax.swing.JButton btnUmjetnikClan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblPridruzi;
    private javax.swing.JLabel llblGlavni;
    private javax.swing.JList<Umjetnik> lstGlavni;
    private javax.swing.JList<String> lstPridruzi;
    private javax.swing.JList<Clan> lstTrazi;
    private javax.swing.JTextField txtTrazi;
    // End of variables declaration//GEN-END:variables


    private void ucitajPodatkeU() {
        DefaultListModel<Umjetnik> m = new DefaultListModel<>();
        obradaU.getPodaci().forEach(s -> m.addElement(s));
        lstGlavni.setModel(m);
    }

     private void ucitajPodatkeA() {
//        lstGlavni.;
//        DefaultListModel<Album> m = new DefaultListModel<>();
//        obradaA.getPodaci().forEach(s -> m.addElement(s));
//        lstGlavni.setModel(m);
    }
    
    
    private void ucitajClanove() {
        DefaultListModel<Clan> m = new DefaultListModel<>();

        obradaC.getPodaci(txtTrazi.getText()).forEach(s -> m.addElement(s));

        lstTrazi.setModel(m);
    }


}
