/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.jp22.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import hr.edunova.jp22.controller.ObradaUmjetnik;
import hr.edunova.jp22.model.Umjetnik;
import hr.edunova.jp22.utility.EdunovaException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Bole
 */
public class Umjetnici extends javax.swing.JFrame {

    private ObradaUmjetnik obrada;
    private Umjetnik entitet;

    /**
     * Creates new form Umjetnici
     */
    public Umjetnici() {
        initComponents();

        DatePickerSettings dps = new DatePickerSettings(new Locale("hr", "HR"));
        DatePickerSettings dps1 = new DatePickerSettings(new Locale("hr", "HR"));
        dps.setFormatForDatesCommonEra("yyyy-MM-dd");
        dps1.setFormatForDatesCommonEra("yyyy-MM-dd");
        dpiDatumP.setSettings(dps);
        dpiDatumK.setSettings(dps1);

        lstUmjetnik.setCellRenderer(new UmjetniciCellRenderer());
        obrada = new ObradaUmjetnik();
        ucitajPodatke();
        grananjePodzanra();
        txtIme.setDocument(new JTextFieldLimit(50));
        txtMjesto.setDocument(new JTextFieldLimit(50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnNazad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUmjetnik = new javax.swing.JList<>();
        jPanel = new javax.swing.JPanel();
        txtIme = new javax.swing.JTextField();
        txtMjesto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        dpiDatumP = new com.github.lgooddatepicker.components.DatePicker();
        dpiDatumK = new com.github.lgooddatepicker.components.DatePicker();
        cmbZanr = new javax.swing.JComboBox<>();
        cmbPodzanr = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Umjetnici");

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setForeground(new java.awt.Color(51, 102, 255));

        btnNazad.setText("Idi nazad");
        btnNazad.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        lstUmjetnik.setForeground(new java.awt.Color(0, 0, 153));
        lstUmjetnik.setToolTipText("");
        lstUmjetnik.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUmjetnikValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstUmjetnik);

        jPanel.setBackground(new java.awt.Color(0, 0, 153));

        txtMjesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMjestoKeyTyped(evt);
            }
        });

        jLabel1.setText("Podatci:");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Ime:");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Žanr:");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Podžanr:");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Mjesto:");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Datum kraja:");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Datum početka:");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        btnDodaj.setText("Dodaj");
        btnDodaj.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setText("Promjeni");
        btnPromjeni.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        dpiDatumP.setBackground(new java.awt.Color(0, 0, 153));

        dpiDatumK.setBackground(new java.awt.Color(0, 0, 153));

        cmbZanr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blues", "Metal", "Hip Hop", "Folk", "Jazz", "Pop", "Punk", "Rock", "EDM", "Country", "Classical Music" }));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPromjeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnObrisi)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbPodzanr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbZanr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dpiDatumP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMjesto)
                            .addComponent(txtIme)
                            .addComponent(dpiDatumK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPodzanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(txtMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(dpiDatumP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpiDatumK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnPromjeni)
                    .addComponent(btnObrisi))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNazad)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        Izbornik izbornik = new Izbornik();
        izbornik.setLocationRelativeTo(null);
        izbornik.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void lstUmjetnikValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUmjetnikValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        entitet = lstUmjetnik.getSelectedValue();
        if (entitet == null) {
            return;
        }

        if (entitet.getDatumpocetka() != null) {
            dpiDatumP.setDate(entitet.getDatumpocetka().toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate());
        }

        if (entitet.getDatumkraja() != null) {
            dpiDatumK.setDate(entitet.getDatumkraja().toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate());
        }

        txtIme.setText(entitet.getIme());
        cmbZanr.setSelectedItem(entitet.getZanr());
        cmbPodzanr.setSelectedItem(entitet.getPodzanr());
        txtMjesto.setText(entitet.getMjesto());
    }//GEN-LAST:event_lstUmjetnikValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        entitet = new Umjetnik();
        try {
            postaviVrijednostiUEntitet();
        } catch (ParseException ex) {
            Logger.getLogger(Umjetnici.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            obrada.create();
            ucitajPodatke();
            ocistiPolja();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(null, ex.getPoruka());
        }

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        entitet = lstUmjetnik.getSelectedValue();
        if (entitet == null) {
            JOptionPane.showMessageDialog(null, "Niste izabrali umjetnika.");
            return;
        }

        try {
            postaviVrijednostiUEntitet();
        } catch (ParseException ex) {
            Logger.getLogger(Umjetnici.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            obrada.update();
            ucitajPodatke();
            ocistiPolja();

        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(null, ex.getPoruka());
        }
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        entitet = lstUmjetnik.getSelectedValue();
        if (entitet == null) {
            JOptionPane.showMessageDialog(null, "Niste izabrali umjetnika.");
            return;
        }

        obrada.setEntitet(entitet);

        try {
            obrada.delete();
            ucitajPodatke();
            ocistiPolja();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(null, ex.getPoruka());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtMjestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMjestoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMjestoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JComboBox<String> cmbPodzanr;
    private javax.swing.JComboBox<String> cmbZanr;
    private com.github.lgooddatepicker.components.DatePicker dpiDatumK;
    private com.github.lgooddatepicker.components.DatePicker dpiDatumP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Umjetnik> lstUmjetnik;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtMjesto;
    // End of variables declaration//GEN-END:variables

    private void ucitajPodatke() {

        DefaultListModel<Umjetnik> m = new DefaultListModel<>();
        obrada.getPodaci().forEach(s -> m.addElement(s));
        lstUmjetnik.setModel(m);

    }

    private void ocistiPolja() {
        txtIme.setText("");
        cmbZanr.setSelectedIndex(0);
        cmbPodzanr.setSelectedIndex(0);
        txtMjesto.setText("");
        dpiDatumP.setDateToToday();
        dpiDatumK.setDateToToday();
    }

    private void postaviVrijednostiUEntitet() throws ParseException {

        entitet.setIme(txtIme.getText());
        entitet.setZanr((String) cmbZanr.getSelectedItem());
        entitet.setPodzanr((String) cmbPodzanr.getSelectedItem());
        entitet.setMjesto(txtMjesto.getText());
        if (dpiDatumP.getDate() != null) {
            entitet.setDatumpocetka(Date.from(dpiDatumP.getDate().atStartOfDay()
                    .atZone(ZoneId.systemDefault())
                    .toInstant()));
        }
        if (dpiDatumK.getDate() != null) {
            entitet.setDatumkraja(Date.from(dpiDatumK.getDate().atStartOfDay()
                    .atZone(ZoneId.systemDefault())
                    .toInstant()));
        }

        obrada.setEntitet(entitet);

    }

    public void grananjePodzanra() {

        cmbZanr.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                switch (cmbZanr.getItemAt(cmbZanr.getSelectedIndex())) {
                    case "Blues":
                        String[] array1 = {"Soul", "Piano", "Acoustic", "Boogie Woogie", "Vaudeville", "Jump", "Chicago",
                            "Swamp"};
                        DefaultComboBoxModel model1 = new DefaultComboBoxModel(array1);
                        cmbPodzanr.setModel(model1);
                        break;
                    case "Metal":
                        String[] array2 = {"Doom", "Heavy", "Industrial", "Power", "Stoner", "Sludge", "Grindcore", "Death",
                            "Progressive", "Speed", "Symphonic", "Neoclassical", "Metalcore", "Drone"};
                        DefaultComboBoxModel model2 = new DefaultComboBoxModel(array2);
                        cmbPodzanr.setModel(model2);
                        break;
                    case "Hip Hop":
                        String[] array3 = {"Abstract", "Trap", "East Coast", "Conscious", "Experimental", "Bounce", "Cloud Rap",
                            "Instrumental", "Southern", "West Coast", "Conscious", "UK", "Memphis Rap", "Hardcore"};
                        DefaultComboBoxModel model3 = new DefaultComboBoxModel(array3);
                        cmbPodzanr.setModel(model3);
                        break;
                    case "Folk":
                        String[] array4 = {"Traditional", "Contemporary", "Bard Music", "Baroque", "American Primitivism", "Neofolk",
                            "Dark", "Throat Singing"};
                        DefaultComboBoxModel model4 = new DefaultComboBoxModel(array4);
                        cmbPodzanr.setModel(model4);
                        break;
                    case "Jazz":
                        String[] array5 = {"Acid", "Avant Garde", "Gypsy", "Fusion", "Swing", "Soul", "Post Bop", "Spiritual",
                            "Revival", "Free", "Flamenco"};
                        DefaultComboBoxModel model5 = new DefaultComboBoxModel(array5);
                        cmbPodzanr.setModel(model5);
                        break;
                    case "Pop":
                        String[] array6 = {"Synthpop", "Psychedelic", "Progressive", "J Pop", "Indie", "Bubblegum", "Art", "Bitpop",
                            "Boy Band"};
                        DefaultComboBoxModel model6 = new DefaultComboBoxModel(array6);
                        cmbPodzanr.setModel(model6);
                        break;
                    case "Punk":
                        String[] array7 = {"Post Hardcore", "Emo", "Post", "Proto", "Art", "Digital Hardcore", "Screamo", "Coldwave",
                            "Ska", "Skate", "Riot Grrrl"};
                        DefaultComboBoxModel model7 = new DefaultComboBoxModel(array7);
                        cmbPodzanr.setModel(model7);
                        break;
                    case "Rock":
                        String[] array8 = {"Alternative", "Comedy", "Emo", "Hard", "Glam", "Garage", "Math", "New Wave", "Indie",
                            "Noise", "Post", "Progressive", "Psychedelic", "Rap", "Opera", "Surf", "Symphonic", "Rock and Roll"};
                        DefaultComboBoxModel model8 = new DefaultComboBoxModel(array8);
                        cmbPodzanr.setModel(model8);
                        break;
                    case "EDM":
                        String[] array9 = {"Electropop", "Glitch", "Grime", "IDM", "Disco", "Folktronica", "Nu Jazz", "Vaportrap",
                            "Wave", "Nightcore"};
                        DefaultComboBoxModel model9 = new DefaultComboBoxModel(array9);
                        cmbPodzanr.setModel(model9);
                        break;
                    case "Country":
                        String[] array10 = {"Americana", "Honky Tonk", "Western Swing", "Contemporary", "Traditional",
                            "Alt", "Progressive"};
                        DefaultComboBoxModel model10 = new DefaultComboBoxModel(array10);
                        cmbPodzanr.setModel(model10);
                        break;
                    case "Classical Music":
                        String[] array11 = {"Modern", "Pibroch", "Slashmaqam", "Cinematic", "Western", "Latin", "Brazilian",
                            "Arabic", "Asian", "Persian"};
                        DefaultComboBoxModel model11 = new DefaultComboBoxModel(array11);
                        cmbPodzanr.setModel(model11);
                        break;
                    default:
                        String[] array12 = {""};
                        DefaultComboBoxModel model12 = new DefaultComboBoxModel(array12);
                        cmbPodzanr.setModel(model12);
                        break;
                }
            }
        });
    }

}
